apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ns.yaml
  - ./satisfactory/ks.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: flux-system
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: satisfactory
