apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mCZ3XnoKN6fp2VM=,iv:lhq7TFQrcuL95Jo78hR4Ud71L3/wfCO3Gvx3oErkCio=,tag:Dzn8DFK7rPaYzjPLaZ38RA==,type:str]
    IPAM_IP_SATISFACTORY: ENC[AES256_GCM,data:fJnqOEF+6ijtA4I=,iv:2Cl82F1VNsjLimuHWYI1n0mVH9+UGKZ9XDAwxWf1r64=,tag:mnMqNXdnHn0nsyIOBaQpOw==,type:str]
sops:
    age:
        - recipient: age1xnjespq5dst3xw0hcdk568lu77mgvam6frefcv7h5pk8vaxdgvrs8ue94k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQmpFMGZJUE1qVXN5QVdx
            ZlR5RGp5OCthWW1xVDBwcG9IcXhJQjI0SWhRCnZMaGN2Vmh0SzhnSWg1MVpQRWFo
            RGordDdYUzVTRElkY1NGSFVwVlVYVWcKLS0tIDFlMlBIdTlUS0ZDMmlHUjU3Zldy
            WTV5WmNJeUVmVkpkbkd3eEF5RDZhT0kKP8n4dNzu4ZhVfrnoNQCQk7UdEFnfPubK
            R257U7J2Cu2Pxia+qPxj+ivQVDInZ7XgkOJfg64mUy/qoOvjXiZzOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T23:37:37Z"
    mac: ENC[AES256_GCM,data:jdiLfGe/TuQdEWFrJYcNm/PLc8vhkbawuIgxl0lH80B8sb4TQkhejMRwawOSVMsDeVVl85kz27qO++zM1WulqLN7FZZVkHzmDpDninkjWCQncx8LrcjCHUx4gF3v8RPCzO5YpMaM6F570QLwLX5gsynakggH530gL+kvtn7QyyE=,iv:BitBMd9XzfbvCWv4w4v3dILGcS9ZkiIs9fBW8YfCCvw=,tag:mpDQJOmLVQ49Dz6Eu/HZcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
